spring:
  application:
    name: secuSession
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/xepdb1
    username: c##idev2
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
  security:
    user:
      name: admin
      password: admin1234
logging:
  level:
    '[org.iclass.secu1]': DEBUG
  pattern:
    console: '%clr(%-5level){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n'
server:
  port: 8081
  